src = ["app"]
target-version = "py312"

[lint]
ignore = [
    "ANN101", # missing-type-self
    "ANN102", # missing-type-cls,
    "ANN204", # Missing return type annotation for __init__
    "COM812", # Trailing comma missing
    "D",      # Missing docstrings
    "E501",   # Line too long
    "EM102",  # Exception must not use an f-string literal
    "ERA001", # Commented-out code
    "FA",     # Missing from __future__ import annotations
    "G004",   # Logging statement uses f-string
    "I001",   # Import block is un-sorted or un-formatted
    "ICN001", # Pandas should be imported as pd
    "ISC001", # Implicitly concatenated string literals on one line
    "N815",   # Mixed-case variables
    "PLC0414", # Import alias does not rename original package
    "S101",   # Use of assert
    "S106",   # Possible hardcoded password
    "TRY003", # Avoid specifying long messages outside the exception class

]

select = ["ALL"]