#!/bin/bash

set -e

cd "$(dirname "$0")/.."

poetry run black --check app
poetry run mypy app
poetry run ruff check app

cd "$(dirname "$0")/.."
mkdir -p test-results
poetry run pytest --junitxml=test-results/junit.xml